name: Syntax Tests

on:
  push:
    paths:
      - '.github/workflows/syntax-tests.yml'
      - '**.sublime-syntax'
      - '**/syntax_test*'
      - '**.tmPreferences'
  pull_request:
    paths:
      - '.github/workflows/syntax-tests.yml'
      - '**.sublime-syntax'
      - '**/syntax_test*'
      - '**.tmPreferences'

jobs:
  main:
    name: Syntax Tests (${{ matrix.build }})
    strategy:
      matrix:
        include:
          - build: 4129     # latest as of 7 Dec 2022
            packages: v4129 # latest as of 7 Dec 2022
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: SublimeText/syntax-test-action@v2
        with:
          build: ${{ matrix.build }}
          default_packages: ${{ matrix.packages }}
