name: Syntax Tests

on:
  push:
    branches:
      - "4075"
    paths:
      - '.github/workflows/syntax-tests.yml'
      - '**.sublime-syntax'
      - '**/syntax_test*'
      - '**.tmPreferences'
  pull_request:
    branches:
      - "4075"
    paths:
      - '.github/workflows/syntax-tests.yml'
      - '**.sublime-syntax'
      - '**/syntax_test*'
      - '**.tmPreferences'

jobs:
  main:
    name: Syntax Tests (${{ matrix.build }})
    strategy:
      matrix:
        include:
          - build: 4143     # last stable build before 4148
            packages: v4143 # last stable build before 4148
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: SublimeText/syntax-test-action@v2
        with:
          build: ${{ matrix.build }}
          default_packages: ${{ matrix.packages }}
          package_name: Just
